name: TrackID

dependencies:
  - python==3.9.11
  - psycopg2==2.8.6
  - pip
  - pip:
    - django==4.0.3
    - djangorestframework==3.13.1
    - djangorestframework-simplejwt==5.1.0
    - gunicorn==20.1.0
    - Pillow==9.0.1
    - flake8==4.0.1
    - drf-yasg==1.20.0
    - django-cors-headers
